prod:
  hosts:
    prod.zavadil.eu:
  vars:
    target_dir: /opt/merch-master
    application_files: conf/prod
    service_name: merch-master
    spring_env: prod
    proxy_port: 8082
    domain: merch-master.zavadil.eu
